### ISSUE TITLE
Mappings not loaded after upgrading to Dev Edition v42

### ISSUE THREAD

**Issue by jjdelc** [gomita/firegestures#102] opened 2015-08-15 00:33 UTC
The new update just landed and the mappings list is empty.
I tried loaded a backup and still shows empty. The gestures are being drawn on screen just that there is no mapping to execute.
It was working fine until a few minutes ago that the update landed (Dev edition V42)

**Comment by summeroff** [comment] 2015-08-15 19:03
I have same issue. 
Firefox-trunk 43.0a1 (2015-08-15), Kubuntu 15.04 x64.  
Issue starts a few updates ago. 
Have tried to reinstall addon. 

Mappings list in "Mapping" tab in addon preferences is empty. Button "add script" do nothing. Drag&Drop script does not work too. 

Mappings backup and restore does not help too. 

In "Main" tab in droplist "Choose a mapping to configure". If chose "View Source" than can see a list of mappings. If press Edit then can see window in which can change "Gesture" but textarea under it is empty and uneditable.

**Comment by RichardNysater** [comment] 2015-08-16 11:04
Yep, I can confirm that I have the exact same issue on the new release of dev edition 42 on windows 8.1.

Great job in general on FireGestures, I didn't realize just how much I rely on it until it no longer worked.

**Comment by jsatt** [comment] 2015-08-18 06:02
+1

**Comment by mfausten** [comment] 2015-08-19 07:15
Yes, I have the same issue. Developer Edition 42.0a2 (2015-08-18), Windows 8.1

**Comment by wenketel** [comment] 2015-08-19 10:02
`Mozilla/5.0 (Windows NT 6.1; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0`
+1，nightly 43.0a1（20150817），win7

**Comment by zslayton** [comment] 2015-08-21 19:39
+1, Developer Edition 42.0a2 (2015-08-21), Windows 7

**Comment by summeroff** [comment] 2015-08-22 11:38
Looks like issue has been fixed in last update 1.10.1
Thanks.

PS: is there some way to restore all mappings to default? Reinstalling addon does not help.

**Comment by gomita** [comment] 2015-08-22 14:33
@summeroff 
Close Firefox, remove 'firegestures.sqlite' in your Firefox profile folder.

**Closed** 2015-08-22 14:33 UTC

**Comment by Kijewski** [comment] 2015-08-22 14:57
99,9% of the users won't find this comment, ...

Why don't you store a version information in firegestures.sqlite? If it is too old (or absent), then discard the file.
